
// import { SUSE_Mono } from 'next/font/google'
import "./globals.css";

// const suseMono = SUSE_Mono({
//   subsets: ['latin'],  // أو أي subset الخط يدعمه
//   weight: ['400','700'], // اختياري بناءً على النسخ المتوفّرة
// })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=SUSE+Mono:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className=" ">
        <h1 className="fixed top-3 left-5 text-4xl z-50 text-white font-bold logo">TRAVEL.</h1>


        {children}
      </body>
    </html>
  );
}
