
// import { SUSE_Mono } from 'next/font/google'
import Link from "next/link";
import Header from "./components/Header";
import "./globals.css";






// const suseMono = SUSE_Mono({
//   subsets: ['latin'],  // أو أي subset الخط يدعمه
//   weight: ['400','700'], // اختياري بناءً على النسخ المتوفّرة
// })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=SUSE+Mono:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className=" ">
      
        {children}
      </body>
    </html>
  );
}
